Training & Inference code for FAcodec
open-mmlab/Amphion pull request #229
Opened 2024-07-02 10:49 UTC by Plachtaa

## ✨ Description

Training & Inference code for FAcodec, include link to pretrained checkpoint

## 🚧 Related Issues

None

## 👨‍💻 Changes Proposed

- [ ] Added new requirements to `env.sh`
- [ ] Added `codec` directory for `bins`, `models`, `egs`

## 🧑‍🤝‍🧑 Who Can Review?

[@zhizhengwu]

## 🛠 TODO

- [ ] To be added...

## ✅ Checklist

- [ ]  Code has been reviewed
- [ ]  Code complies with the project's code standards and best practices
- [ ]  Code has passed all tests
- [ ]  Code does not affect the normal use of existing features
- [ ]  Code has been commented properly
- [ ]  Documentation has been updated (if applicable)
- [ ]  Demo/checkpoint has been attached (if applicable)

2024-07-03 20:49 UTC, RMSnow requested changes
Thanks for the great works and high-quality code from @Plachtaa! There are some files need to be added the copyright information. Let @HeCheng0625 double check the readme of FACodec!

2024-07-03 20:49 UTC, RMSnow commented on models/codec/facodec/modules/attentions.py
> +import copy
Add the copyright information

2024-07-03 20:49 UTC, RMSnow commented on models/codec/facodec/modules/layers.py
> +import math
Add the copyright information

2024-07-03 20:49 UTC, RMSnow commented on modules/dac/model/base.py
> +import math
Add the copyright information

2024-07-03 20:49 UTC, RMSnow commented on modules/dac/model/dac.py
> +import math
Add the copyright information

2024-07-03 20:49 UTC, RMSnow commented on modules/dac/model/discriminator.py
> +import torch
Add the copyright information

2024-07-03 20:49 UTC, RMSnow commented on modules/dac/model/encodec.py
> +# Copyright (c) Meta Platforms, Inc. and affiliates.
Hi @jiaqili3, please help to revise the copyright information for such external modules

2024-07-03 20:49 UTC, RMSnow commented on modules/dac/nn/__init__.py
> +from . import layers
Add the copyright information

2024-07-03 20:49 UTC, RMSnow commented on modules/dac/nn/layers.py
> +import numpy as np
Add the copyright information

2024-07-03 20:49 UTC, RMSnow commented on modules/dac/nn/loss.py
> +import typing
Add the copyright information

2024-07-03 20:49 UTC, RMSnow commented on modules/dac/nn/quantize.py
> +from typing import Union
Add the copyright information

2024-07-03 20:49 UTC, RMSnow commented on egs/codec/FAcodec/README.md
Hi @HeCheng0625, please help to polish this readme. Can we release FACodec's checkpoint in Amphion?

2024-07-07 12:08 UTC, Plachtaa commented
Hi @RMSnow thanks a lot for reviewing the code! I apologize for the late reply. I have just added copyright statements to all newly added files and source of code where necessary. Please help me check whether the format is correct.
Thanks!

2024-07-12 02:10 UTC, jiaqili3 approved these changes
Looks good to me.

2024-07-13 09:24 UTC, xinkez commented on egs/codec/FAcodec/train.sh
No "exp_libritts.json" file?

2024-07-13 09:44 UTC, Plachtaa commented on egs/codec/FAcodec/train.sh
For ease of data preparation, dataset is denoted as a single directory, where audio samples are recursively searched and loaded, as no transcriptions are required.

2024-07-22 11:51 UTC, jiaqili3 commented
Hi @Plachtaa , could you use black formatting to format the code to pass the code style check? The command is just "black .", thanks!

2024-07-25 17:19 UTC, Plachtaa commented
> Hi @Plachtaa , could you use black formatting to format the code to pass the code style check? The command is just "black .", thanks!

Sorry for late reply, I have reformatted all changed & new files with black formatter

2024-08-04 07:02 UTC, merged