split and process valid set
open-mmlab/Amphion pull request #25
Opened 2023-12-12 13:03 UTC by lmxue

update files:
* preprocessors/libritts.py
* preprocessors/ljspeech.py
* preprocessors/metadata.py

2023-12-12 15:39 UTC, RMSnow requested changes

2023-12-12 15:39 UTC, RMSnow commented on preprocessors/metadata.py
What will happen when processing other datasets except for libritts and ljspeech? I suspect that line39 will cause a bug, since there is none `valid.json` for others. 

Besides, is there any corresponding design for the valid and test dataset in **trainer**?

2023-12-12 19:15 UTC, lmxue commented on preprocessors/metadata.py
rewrite the metadata.py to automatically adapt different json files.

2023-12-14 14:54 UTC, RMSnow requested changes

2023-12-14 15:35 UTC, RMSnow approved these changes

2023-12-14 15:36 UTC, merged

2026-03-02 04:37 UTC, wyywwi reviewed
Hi, thank you for submitting this PR to fix the validation set issue.

However, I noticed a slightly confusing detail: in preprocessors/ljspeech.py, the test set lines are used directly to create valid.json, yet in fs2.json, the configuration is set to valid_file: "test.json".

Is this **intentional**, or is it a **typo**? If it’s the latter, I’d be happy to submit a fix for it.