Add Debatts Some Code
open-mmlab/Amphion pull request #295
Opened 2024-10-25 15:55 UTC by hyq-hub

## ✨ Description

[Please describe the background, purpose, changes made, and how to test this PR]

## 🚧 Related Issues

[List the issue numbers related to this PR]

## 👨‍💻 Changes Proposed

- [ ] change1
- [ ] ...

## 🧑‍🤝‍🧑 Who Can Review?

[Please use the '@' symbol to mention any community member who is free to review the PR once the tests have passed. Feel free to tag members or contributors who might be interested in your PR.]

## 🛠 TODO

- [ ] task1
- [ ] ...

## ✅ Checklist

- [ ]  Code has been reviewed
- [ ]  Code complies with the project's code standards and best practices
- [ ]  Code has passed all tests
- [ ]  Code does not affect the normal use of existing features
- [ ]  Code has been commented properly
- [ ]  Documentation has been updated (if applicable)
- [ ]  Demo/checkpoint has been attached (if applicable)

2024-10-28 09:14 UTC, hyq-hub commented
Who Can Review?
@RMSnow @HeCheng0625 @jiaqili3

2024-10-28 11:24 UTC, yuantuo666 requested changes
Adding a README to introduce Debatts, also an env.sh about environment configuration file if needed.

2024-10-28 11:24 UTC, yuantuo666 commented on models/tts/debatts/t2s_model_new.py
> +        phone_ids,  # the phones of prompt and target should be concatenated together。在实际使用中，phone_ids是文本的token输入
It's better to use English comments in the code. It's the same for other files.

2024-10-28 11:24 UTC, yuantuo666 commented on models/tts/debatts/utils/tool.py
use English comments.

2024-10-28 11:24 UTC, yuantuo666 commented on models/tts/debatts/utils/logger.py
use English comments.

2024-10-28 11:24 UTC, yuantuo666 commented on models/tts/debatts/utils/g2p_new/__init__.py
use English comments.

2024-10-28 13:14 UTC, HeCheng0625 commented on models/tts/debatts/t2s_sft_dataset_new.py
Remove "new" where it is not needed.

2025-01-02 03:41 UTC, jiaqili3 approved these changes
lgtm

2025-01-02 04:17 UTC, merged