Add NaturalSpeech2
open-mmlab/Amphion pull request #35
Opened 2023-12-16 15:46 UTC by HeCheng0625

Add NaturalSpeech2

2023-12-17 10:02 UTC, HeCheng0625 commented
Add NaturalSpeech2 models, train, and inference. NS2 predicts latent of encodec, and use decoder of encodec to generate wavform. We also offer a pretrained checkpoint (trained on LibriTTS) for user to inference.

2023-12-17 13:17 UTC, RMSnow commented
Where is the pretrained checkpoint? And are there any generated samples?

2023-12-18 04:28 UTC, lmxue commented on egs/tts/NaturalSpeech2/run_inference.sh
Please merge run_inference.sh and run_trian.sh into a single file, i.e., run.sh, and provide a recipe for NaturalSpeech2.

2023-12-18 04:36 UTC, lmxue commented on models/tts/naturalspeech2/base_trainer.py
What's the difference between this trainer and TTS trainer in models/tts/base/tts_trainer.py?

2023-12-18 04:40 UTC, lmxue commented on models/tts/naturalspeech2/ns2_trainer.py
Why doesn't the NS2 trainer directly inherit TTS trainer (defined in models/tts/base/tts_trainer.py) but instead inherit a newly defined trainer that is similar to the TTS trainer?

2023-12-18 04:41 UTC, lmxue commented on models/tts/naturalspeech2/prior_encoder.py
It would be better to move this module to the directory of modules/encoder.

2023-12-18 04:42 UTC, HeCheng0625 commented on models/tts/naturalspeech2/prior_encoder.py
why

2023-12-18 05:06 UTC, lmxue commented on models/tts/naturalspeech2/wavenet.py
Future improvement: merge this wavenet with Amphion wavenet vocoder (https://github.com/open-mmlab/Amphion/blob/main/models/vocoders/autoregressive/wavenet/wavenet.py)

2023-12-18 07:31 UTC, RMSnow requested changes
Add the copyright information for all the newly added files, including `.py` and `.sh` files.

2023-12-18 07:31 UTC, RMSnow commented on models/tts/naturalspeech2/ns2_trainer.py
> Why doesn't the NS2 trainer directly inherit TTS trainer (defined in models/tts/base/tts_trainer.py) but instead inherit a newly defined trainer that is similar to the TTS trainer?

Same question

2023-12-18 07:31 UTC, RMSnow commented on models/tts/naturalspeech2/prior_encoder.py
I'm not sure about your discussions. A general advice: if `prior_encoder.py` can be used commonly for other model except for ns2, then you need to move it into `modules`.

2023-12-18 07:31 UTC, RMSnow commented on models/tts/naturalspeech2/wavenet.py
> Future improvement: merge this wavenet with Amphion wavenet vocoder (https://github.com/open-mmlab/Amphion/blob/main/models/vocoders/autoregressive/wavenet/wavenet.py)

Approve for the "merge" idea. This name `wavenet.py` is confusing to some extent. It is not a vocoder. I think it is more like `diffwavenet`, which has existed in Amphion: 
https://github.com/open-mmlab/Amphion/blob/b17eea80db16c7e566a7acb426e69ed8f25d3e8e/modules/diffusion/bidilconv/bidilated_conv.py#L14

 @HeCheng0625 You can merge this `wavenet.py` with the existing one.

2023-12-18 08:54 UTC, HeCheng0625 commented on models/tts/naturalspeech2/ns2.py
fix it

2023-12-18 09:01 UTC, HeCheng0625 commented on models/tts/naturalspeech2/wavenet.py
I will do it future. Now the wavenet is designed only for NS2. And it has a lot of different input compared to BiDilConv.

2023-12-18 09:01 UTC, lmxue commented on models/tts/naturalspeech2/prior_encoder.py
I think the `models` folder should only contain the model (e.g., fastspeech2, vits, valle) only, the related module should be placed in the `modules` folder, especially since you have created the folder `modules/naturalspeech2`.

2023-12-18 09:16 UTC, HeCheng0625 commented on models/tts/naturalspeech2/base_trainer.py
Because some initialization is useless for ns2. I don't want to inherit TTS trainer.

2023-12-18 11:33 UTC, HeCheng0625 commented
> Where is the pretrained checkpoint? And are there any generated samples?

Paper: https://arxiv.org/abs/2304.09116
CKPT: https://huggingface.co/amphion/naturalspeech2_libritts
Demo: https://huggingface.co/spaces/amphion/NaturalSpeech2

2023-12-18 13:26 UTC, lmxue approved these changes

2023-12-18 13:40 UTC, RMSnow approved these changes

2023-12-18 13:40 UTC, merged