add core code of valle
open-mmlab/Amphion pull request #4
Opened 2023-12-01 16:09 UTC by lmxue

add valle core code, including
* bins/tts
* config/valle.json
* egs/tts/VALLE
* models/tts/valle

2023-12-01 17:11 UTC, RMSnow approved these changes
Leave the comments as the next improvement

2023-12-01 17:11 UTC, RMSnow commented on processors/content_extractor.py
>      Extractor for content features
Provide the comments of `extract_phoneme` related code

2023-12-01 17:11 UTC, RMSnow commented on processors/content_extractor.py
> +    if cfg.preprocess.extract_phoneme:
The current code will make SVC and TTS entangle unnecessarily. Move Line545-589 to a new function.

2023-12-02 01:46 UTC, zhizhengwu commented on bins/tts/inference.py
> +    VALLEInference.add_arguments(parser)
this looks like VALLEInference is used no matter what type of the model.

2023-12-02 01:48 UTC, zhizhengwu commented on bins/tts/preprocess.py
> +        types = ["test"]
repeating lines: 32 - 39

2023-12-02 01:48 UTC, zhizhengwu commented on bins/tts/preprocess.py
>          dataset_file = os.path.join(dataset_output, "{}.json".format(dataset_type))
duplicating line 78?

2023-12-02 01:49 UTC, zhizhengwu commented on bins/tts/train.py
> +    # # CUDA settings
No need to add one more '#'

2023-12-02 01:50 UTC, zhizhengwu commented
We should provide demos/samples in a PR

2023-12-02 01:54 UTC, RMSnow requested changes

2023-12-02 01:54 UTC, RMSnow commented on config/base.json
> -    "gradient_accumulation_step": 1,
why delete?

2023-12-02 01:54 UTC, RMSnow commented on config/base.json
Move all the configs about TTS into a TTS's config base json

2023-12-02 01:54 UTC, RMSnow commented on processors/acoustic_extractor.py
> +        if cfg.preprocess.extract_acoustic_token:
Do not modify `__extract_utt_acoustic_features` anymore. It is not a common extraction pipeline now. See `extract_utt_acoustic_features_tts` (line221) and `extract_utt_acoustic_features_vocoder`(line233) as reference. Please move all the functions of TTS's acoustic feature extraction into line221.

2023-12-02 02:06 UTC, zhizhengwu commented on bins/tts/inference.py
> +        help="Text",
'Text to be synthesized' is more informative than 'Text'

2023-12-02 02:16 UTC, RMSnow approved these changes

2023-12-02 02:37 UTC, merged