Adding Contribution Guideline for Amphion
open-mmlab/Amphion pull request #92
Opened 2024-01-06 11:48 UTC by HarryHe11

**✨ Description:** 

Adding contribution guidelines, pull request template, and code of conduct.

**🚧 Related Issues:** 

No related issues.

**👨‍💻 Changes Proposed:** 

- [1] Add contribution guidelines (CONTRIBUTING.md)
- [2] Add pull request template (pull_request_template.md)
- [3] Add code of conduct (CODE_OF_CONDUCT.md)
- [4] Updated main README.md

**🛠 TODO**

No TODO.

**✅ Checklist:**

- [✅]  Code has been reviewed
- [✅]  Code complies with the project's code standards and best practices
- [✅]  Code has passed all tests
- [✅]  Code does not affect the normal use of existing features
- [✅]  Documentation has been updated

2024-01-07 13:02 UTC, RMSnow requested changes
Nice work!

2024-01-07 13:02 UTC, RMSnow commented on .github/pull_request_template.md
Add another section: `Who can review`? You can refer to [huggingface/accelerate](https://github.com/huggingface/accelerate/pull/2310). This will encourage the contributors to notify some necessary reviewers (using `@`).

2024-01-07 13:07 UTC, RMSnow commented on .github/pull_request_template.md
Another point: use `- [ ]` instead of `- [✅]` in checklist. The accelerate repo also exemplifies. For example:

- [x] finished
- [ ] TBD

2024-01-08 05:53 UTC, HarryHe11 commented
> Nice work!

Hi Xueyao, thank you so much for reviewing my pr. I've updated this pr according to your feedback, please check the latest commit!

2024-01-08 11:44 UTC, lmxue commented on .github/pull_request_template.md
> +**✅ Checklist:**
Maybe the following checklist can be added here:
- [ ] Demo/checkpoint has been uploaded (if applicable)

2024-01-08 11:48 UTC, lmxue requested changes
Thanks for your efforts. Please check the comment.

2024-01-09 06:34 UTC, HarryHe11 commented
> Thanks for your efforts. Please check the comment.

Hi Liumeng, thank you so much for reviewing my pr. I've resolved your comments. Please check the latest commit!

2024-01-09 07:25 UTC, lmxue approved these changes

2024-01-09 08:57 UTC, RMSnow approved these changes

2024-01-09 08:59 UTC, merged