Add WavLM speaker similarity for evaluation
open-mmlab/Amphion pull request #97
Opened 2024-01-09 11:28 UTC by HeCheng0625

## ✨ Description

The PR add WavLM speaker similarity for evalution, which is widely used for TTS (e.g. Mega-TTS), VC (e.g. LM-VC, UniAudio).

## 🚧 Related Issues

No

## 👨‍💻 Changes Proposed

- [ ] Add wavlm_similarity in `evaluation/metrics/similarity/wavlm_similarity.py`
- [ ] Add `wavlm_similarity` in `METRIC_FUNC`

## 🧑‍🤝‍🧑 Who Can Review?

@lmxue @zhizhengwu @RMSnow 

## 🛠 TODO

No

## ✅ Checklist

- [ ]  Code has been reviewed
- [x]  Code complies with the project's code standards and best practices
- [x]  Code has passed all tests
- [x]  Code does not affect the normal use of existing features
- []  Code has been commented properly
- [ ]  Documentation has been updated (if applicable)
- [ ]  Demo/checkpoint has been attached (if applicable)

2024-01-09 11:43 UTC, RMSnow approved these changes
Nice work!

2024-01-09 11:46 UTC, RMSnow requested changes
Could you also refine the doc `egs/metrics/README.md`?

2024-01-09 16:30 UTC, lmxue commented on evaluation/metrics/similarity/wavlm_similarity.py
> +def extract_wavlm_similarity(target_path, reference_path):
Could you please add comments for this new function? Adding comments is also a part of the PR checklist.

2024-01-09 16:30 UTC, lmxue requested changes
Please add comments for the new function.

2024-01-09 23:35 UTC, lmxue approved these changes

2024-01-11 02:23 UTC, RMSnow approved these changes
Well done!

2024-01-11 02:24 UTC, merged